window.alert("HEY,ARE YOU MY BABY? IF YES, CLICK OKAY AND CLICK EVERY PIC IN THIS PAGE, TO SEE THE COMMENT HEHE")
window.alert("I WANT TO GREET U A HAPPY GF DAY HEHE, SANA DI NA TAYO MA ISSUE SA BARANGAY NA 'TO HUHU EME HAHAHA")
window.alert("HAPPY NATIONAL GIRLFRIEND DAY BABY!!!!!")